version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_doc
      MYSQL_USER: db_client
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: php_client
    volumes:
      - ./client:/var/www/html
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: database
      MYSQL_USER: db_client
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: docker_doc_dev
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
